/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class MainVuelos extends javax.swing.JFrame {

    /**
     * Creates new form MainVuelos
     */
    public static Lista[] terminales;
    public static Cola pista = new Cola();
    public static Cola mantenimiento = new Cola();
    
    public MainVuelos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        vuelosB = new javax.swing.JMenu();
        insertarV = new javax.swing.JMenuItem();
        mandarP = new javax.swing.JMenuItem();
        pistaB = new javax.swing.JMenu();
        jPistaD = new javax.swing.JMenuItem();
        mantenimientoB = new javax.swing.JMenu();
        jMantenimiento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Vuelos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        vuelosB.setText("Vuelos");

        insertarV.setText("Insertar vuelo");
        insertarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarVActionPerformed(evt);
            }
        });
        vuelosB.add(insertarV);

        mandarP.setText("Mandar vuelo a pista");
        mandarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandarPActionPerformed(evt);
            }
        });
        vuelosB.add(mandarP);

        jMenuBar1.add(vuelosB);

        pistaB.setText("Pista");
        pistaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaBActionPerformed(evt);
            }
        });

        jPistaD.setText("Pista de despegue");
        jPistaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPistaDActionPerformed(evt);
            }
        });
        pistaB.add(jPistaD);

        jMenuBar1.add(pistaB);

        mantenimientoB.setText("Mantenimiento");

        jMantenimiento.setText("Mantenimiento");
        jMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMantenimientoActionPerformed(evt);
            }
        });
        mantenimientoB.add(jMantenimiento);

        jMenuBar1.add(mantenimientoB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int num_term;
        num_term = Integer.parseInt(JOptionPane.showInputDialog("¿Cuántas terminales?"));
        terminales = Manipula.crearTerm(num_term);

    }//GEN-LAST:event_formWindowOpened

    private void insertarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarVActionPerformed
        new VtnInsertar().setVisible(true);
    }//GEN-LAST:event_insertarVActionPerformed

    private void mandarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandarPActionPerformed
        new VtnMPista().setVisible(true);
    }//GEN-LAST:event_mandarPActionPerformed

    private void pistaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaBActionPerformed
        
    }//GEN-LAST:event_pistaBActionPerformed

    private void jPistaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPistaDActionPerformed
        new VtnDespegue().setVisible(true);
    }//GEN-LAST:event_jPistaDActionPerformed

    private void jMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMantenimientoActionPerformed
        new Mantenimiento().setVisible(true);
    }//GEN-LAST:event_jMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem insertarV;
    private javax.swing.JMenuItem jMantenimiento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jPistaD;
    private javax.swing.JMenuItem mandarP;
    private javax.swing.JMenu mantenimientoB;
    private javax.swing.JMenu pistaB;
    private javax.swing.JMenu vuelosB;
    // End of variables declaration//GEN-END:variables
}
