/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class VtnMPista extends javax.swing.JFrame {

    /**
     * Creates new form VtnMPista
     */
    private int pos;

    public VtnMPista() {
        initComponents();
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTerminal = new javax.swing.JComboBox<>();
        jVuelo = new javax.swing.JComboBox<>();
        jPista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mandar a pista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Terminal: ");

        jLabel2.setText("Vuelo: ");

        jTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTerminalActionPerformed(evt);
            }
        });

        jVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVueloActionPerformed(evt);
            }
        });

        jPista.setText("Mandar a pista");
        jPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPistaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addComponent(jVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPista)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPista)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVueloActionPerformed
        MainVuelos.terminales[Integer.parseInt((String) jTerminal.getSelectedItem()) - 1].desplegarV((String) jVuelo.getSelectedItem(), jTextArea1);
    }//GEN-LAST:event_jVueloActionPerformed

    private void jPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPistaActionPerformed
        Vuelo temp;
        Nodo vp;
        try {
            vp = MainVuelos.terminales[Integer.parseInt((String) jTerminal.getSelectedItem()) - 1].elimina((String) jVuelo.getSelectedItem());
            //temp = (Vuelo) MainVuelos.terminales[Integer.parseInt((String) jTerminal.getSelectedItem()) - 1].elimina((String) jVuelo.getSelectedItem()).getObj();
            temp = (Vuelo) vp.getObj();
            MainVuelos.pista.insertar(vp);
            jVuelo.removeItem(jVuelo.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Vuelo " + temp.getNum_vuelo() + " de la terminal " + temp.getNum_t() + " ingrasado a la pista");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "No hay ningún vuelo por ingresar a la pista", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jPistaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Manipula.cargaCombo(MainVuelos.terminales, jTerminal);
    }//GEN-LAST:event_formWindowOpened

    private void jTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTerminalActionPerformed
        pos = Integer.parseInt((String) jTerminal.getSelectedItem()) - 1;
        try {
            jVuelo.removeAllItems();
            Manipula.cargaCombo(MainVuelos.terminales[pos].getR(), jVuelo);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No hay vuelos en esta terminal", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jTerminalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnMPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnMPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnMPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnMPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnMPista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jPista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jTerminal;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jVuelo;
    // End of variables declaration//GEN-END:variables
}
